### PR TITLE
[WIP/RFC] Pointer indirection

### LINKED ISSUE #163: garbage collector found invalid heap pointer: Go 1.4
After upgrading from go1.3 to go1.4, I'd get a runtime crash most of the time.  It crashes for various reasons (nil tree walker callback, invalid heap pointer...). Here is a scaled down version of the code that demonstrates the problem (runtime crashes most of the time).  Run this code with an argument pointing at a git repository like git2go.

```go
package main

import (
	"fmt"
	"github.com/libgit2/git2go"
	"os"
	"strings"
)

type MyRepo struct {
	*git.Repository
}

func (repository *MyRepo) foo(path string, treeEntry *git.TreeEntry) int {
	if git.ObjectBlob != treeEntry.Type {
		return 0 // continue
	}

	if !strings.HasSuffix(treeEntry.Name, ".go") {
		return 0 // continue
	}

	blob, err := repository.Repository.LookupBlob(treeEntry.Id)
	defer blob.Free()
	if err != nil {
		panic(err)
	}

	if blob.Size() > 10000 {
		return 0 // continue
	}

	contents := blob.Contents()
	if contents == nil {
		panic("nil contents")
	}
	fmt.Printf("%q", path, treeEntry.Name, string(contents))
	fmt.Println()

	return 0 // continue
}

func main() {
	filename := os.Args[1]

	repository, err := git.OpenRepository(filename)
	if err != nil {
		panic(err)
	}
	defer repository.Free()

	myRepo := MyRepo{repository}

	revWalk, err := repository.Walk()
	if err != nil {
		panic(err)
	}
	defer revWalk.Free()

	// Start out at the head
	err = revWalk.PushHead()
	if err != nil {
		panic(err)
	}

	err = revWalk.Iterate(func(commit *git.Commit) bool {
		defer commit.Free()

		tree, err := commit.Tree()
		if err != nil {
			panic(err)
		}
		defer tree.Free()

		err = tree.Walk(myRepo.foo)
		if err != nil {
			panic(err)
		}

		return true
	})

	if err != nil {
		panic(err)
	}
}
```

Some errors that come from the above code:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40f4299]

goroutine 1 [running]:
github.com/libgit2/git2go.CallbackGitTreeWalk(0x438a520, 0x51008e0, 0xc208071e40, 0x0)
	/Users/maleticm/.gvm/pkgsets/go1.4/jack/src/github.com/libgit2/git2go/tree.go:99 +0x79
github.com/libgit2/git2go._Cfunc__go_git_treewalk(0x5100850, 0x0, 0xc208069e40, 0x0)
	/Users/maleticm/.gvm/pkgsets/go1.4/jack/src/github.com/libgit2/git2go/:402 +0x43
github.com/libgit2/git2go.Tree.Walk(0x5100850, 0xc20802c018, 0x5100850, 0xc208069e80, 0x0, 0x0)
```

```
runtime: garbage collector found invalid heap pointer *(0xc208069cd0+0x10)=0xc208083e40 span=0xc20807e000-0xc208083800-0xc208084000 state=0
fatal error: invalid heap pointer

runtime stack:
runtime.throw(0x437df83)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/panic.go:491 +0xad fp=0x7fff5fbfea18 sp=0x7fff5fbfe9e8
scanblock(0xc208069cd0, 0x20, 0x42c12e4)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/mgc0.c:378 +0x551 fp=0x7fff5fbfeb58 sp=0x7fff5fbfea18
scanframe(0x7fff5fbfec60, 0x0, 0x1)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/mgc0.c:740 +0x1c2 fp=0x7fff5fbfebc8 sp=0x7fff5fbfeb58
```

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x40f4299]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x426ec90, 0x5)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/panic.go:503 +0x8e fp=0xc208069c40 sp=0xc208069c28
runtime.sigpanic()
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/sigpanic_unix.go:29 +0x261 fp=0xc208069c90 sp=0xc208069c40
github.com/libgit2/git2go.CallbackGitTreeWalk(0x438a520, 0x5009680, 0xc208073e40, 0x0)
```

### PR DESCRIPTION
**Pull request by pks-t**
This pull request fixes issues with Go callbacks that are handed over to C functions. As of Go 1.4 it is not possible to hand over Go pointers into C code as the garbage collector is allowed to copy around the stack, causing pointers to become invalid (see golang/go#8310 and golang/go#10303 for more information).

@carlosmn proposed an interface HandleList for pointer indirection which provides a global map of data that is to be tracked. Instead of handing in pointers we now instead hand over an index that points to the corresponding entry in this map.

This PR adds the HandleList implemented by @carlosmn, fixes some issues with it and adjusts code that hands over Go pointers into C code to use handles instead. Still missing is the remote.go code, as I am running into some error there ('runtime: garbage collector found invalid heap pointer *(0xc208063cd0+0x18)=0x1 s=nil') that I've not been able to fix.

This PR also fixes #163.

### CODE REVIEW

**Comment by pks-t** [comment]
I guess it makes sense to not fix the remotes code but instead wait for libgit2/libgit2#3066 to be merged, as the interface will change anyway. The rest could be merged independetly of this, though.

File: index.go [hunk 1]
```diff
@@ -207,8 +210,13 @@ func (v *Index) RemoveAll(pathspecs []string, callback IndexMatchedPathCallback)
...
 func indexMatchedPathCallback(cPath, cMatchedPathspec *C.char, payload unsafe.Pointer) int {
-	callback := (*IndexMatchedPathCallback)(payload)
-	return (*callback)(C.GoString(cPath), C.GoString(cMatchedPathspec))
+	if payload == nil {
+		return 0
+	} else if callback, ok := pointerHandles.Get(payload).(IndexMatchedPathCallback); ok {
+		return callback(C.GoString(cPath), C.GoString(cMatchedPathspec))
+	} else {
+		return -1
+	}
```
Comment (carlosmn) [inline index.go]: The payload wasn't optional before, it shouldn't be now.

File: submodule.go [hunk 2]
```diff
@@ -97,17 +97,24 @@ func (repo *Repository) LookupSubmodule(name string) (*Submodule, error) {
...
+func SubmoduleVisitor(csub unsafe.Pointer, name *C.char, handle unsafe.Pointer) C.int {
 	sub := &Submodule{(*C.git_submodule)(csub)}
-	fct := *(*SubmoduleCbk)(cfct)
-	return (C.int)(fct(sub, C.GoString(name)))
+
+	if callback, ok := pointerHandles.Get(handle).(SubmoduleCbk); ok {
+		return (C.int)(callback(sub, C.GoString(name)))
+	} else {
+		return -1
+	}
```
Comment (carlosmn) [inline submodule.go]: Same here, if there is no callback, we should panic.

File: tree.go [hunk 3]
```diff
@@ -93,19 +93,25 @@ type TreeWalkCallback func(string, *TreeEntry) int
...
 	root := C.GoString((*C.char)(_root))
 	entry := (*C.git_tree_entry)(_entry)
-	callback := *(*TreeWalkCallback)(ptr)
 
-	return C.int(callback(root, newTreeEntry(entry)))
+	if callback, ok := pointerHandles.Get(ptr).(TreeWalkCallback); ok {
+		return C.int(callback(root, newTreeEntry(entry)))
+	} else {
+		return C.int(-1)
+	}
```
Comment (carlosmn) [inline tree.go]: And here, we cannot legally get to a situation where there is no callback.

File: index.go (hunk 1 above)
Comment (pks-t) [inline index.go]: Well, if you take a look at index_test.go:TestIndexAddAllNoCallback it seems as if the callback was optional after all.

**Comment by pks-t** [comment]
I've changed the code to panic when no treewalk/submodulevisitor callback could be found. The `indexMatchedPathCallback` payload may be `nil`, though, as it is allowed to call `AddAll` without a callback.

**Comment by pks-t** [comment]
Any comments regarding this PR?

File: index.go (hunk 1 above)
Comment (carlosmn) [inline index.go]: It is optional to pass, but we only tell libgit2 to call `indexMatchedPathCallback` if the caller did pass in the callback. This function only gets called if there *is* a callback.

**Comment by taylorchu** [comment]
I tested "git diff" with go1.4. It solves the panic caused by GC.

File: index.go (hunk 1 above)
Comment (pks-t) [inline index.go]: Okay, agreed and fixed.

**Comment by carlosmn** [comment]
There's still callbacks where we check whether the pointer is valid. If we do not find the handle in the list, there is no way we can continue running the program, as the state has been corrupted. We should either assume that the callback is correct, or panic if the retrieval fails.

**Comment by taylorchu** [comment]
@pks-t 

The latest commits broke it again.

```
runtime: garbage collector found invalid heap pointer *(0xc20806bc88+0x18)=0x1 s=nil
fatal error: invalid heap pointer

runtime stack:
runtime.throw(0x92fb83)
	/usr/lib/go/src/runtime/panic.go:491 +0xad fp=0x7ffd22631088 sp=0x7ffd22631058
scanblock(0xc20806bc88, 0x28, 0x6681c8)
	/usr/lib/go/src/runtime/mgc0.c:381 +0x551 fp=0x7ffd226311c8 sp=0x7ffd22631088
scanframe(0x7ffd226312d0, 0x0, 0x1)
	/usr/lib/go/src/runtime/mgc0.c:743 +0x1c2 fp=0x7ffd22631238 sp=0x7ffd226311c8
runtime.gentraceback(0x44d160, 0xc20806b9d0, 0x0, 0xc208000120, 0x0, 0x0, 0x7fffffff, 0x7ffd22631380, 0x0, 0x0, ...)
	/usr/lib/go/src/runtime/traceback.go:311 +0x7a8 fp=0x7ffd22631328 sp=0x7ffd22631238
scanstack(0xc208000120)
	/usr/lib/go/src/runtime/mgc0.c:780 +0x21c fp=0x7ffd22631398 sp=0x7ffd22631328
markroot(0xc208010000, 0x5)
	/usr/lib/go/src/runtime/mgc0.c:556 +0xe7 fp=0x7ffd226313f8 sp=0x7ffd22631398
runtime.parfordo(0xc208010000)
	/usr/lib/go/src/runtime/parfor.c:76 +0xb2 fp=0x7ffd22631478 sp=0x7ffd226313f8
gc(0x7ffd226315b0)
	/usr/lib/go/src/runtime/mgc0.c:1442 +0x25e fp=0x7ffd22631590 sp=0x7ffd22631478
runtime.gc_m()
	/usr/lib/go/src/runtime/mgc0.c:1371 +0xe0 fp=0x7ffd226315c8 sp=0x7ffd22631590
runtime.onM(0x7ffd22631db8)
	/usr/lib/go/src/runtime/asm_amd64.s:257 +0x68 fp=0x7ffd226315d0 sp=0x7ffd226315c8
runtime.mstart()
	/usr/lib/go/src/runtime/proc.c:818 fp=0x7ffd226315d8 sp=0x7ffd226315d0

goroutine 1 [garbage collection, locked to thread]:
runtime.switchtoM()
	/usr/lib/go/src/runtime/asm_amd64.s:198 fp=0xc20806b9d8 sp=0xc20806b9d0
runtime.gogc(0x7fea00000000)
	/usr/lib/go/src/runtime/malloc.go:469 +0x1cf fp=0xc20806ba10 sp=0xc20806b9d8
runtime.mallocgc(0x30, 0x0, 0x7fea00000003, 0xc20802b4ca)
	/usr/lib/go/src/runtime/malloc.go:341 +0x391 fp=0xc20806bac0 sp=0xc20806ba10
runtime.rawstring(0x2b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/string.go:195 +0x93 fp=0xc20806baf0 sp=0xc20806bac0
runtime.gostringn(0x12abd58, 0x2b, 0x0, 0x0)
	/usr/lib/go/src/runtime/string.go:275 +0x57 fp=0xc20806bb50 sp=0xc20806baf0
github.com/taylorchu/git2go._Cfunc_GoStringN(0x12abd58, 0xc20000002b, 0x0, 0x0)
	/home/march/src/github.com/taylorchu/git2go/:321 +0x4b fp=0xc20806bb78 sp=0xc20806bb50
github.com/taylorchu/git2go.diffLineFromC(0x127e0c0, 0x7ffd22631a30, 0x7ffd226316c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/march/src/github.com/taylorchu/git2go/diff.go:121 +0x42 fp=0xc20806bbd0 sp=0xc20806bb78
github.com/taylorchu/git2go.diffForEachLineCb(0x127e0c0, 0x7ffd22631a30, 0x7ffd226316c0, 0x1, 0x0)
	/home/march/src/github.com/taylorchu/git2go/diff.go:333 +0xf8 fp=0xc20806bc88 sp=0xc20806bbd0
runtime.call64(0x7ffd22631600, 0x7ffd22631680, 0x28)
	/usr/lib/go/src/runtime/asm_amd64.s:403 +0x45 fp=0xc20806bcd0 sp=0xc20806bc88
runtime.cgocallbackg1()
	/usr/lib/go/src/runtime/cgocall.go:239 +0x12a fp=0xc20806bd30 sp=0xc20806bcd0
runtime.cgocallbackg()
	/usr/lib/go/src/runtime/cgocall.go:193 +0x6e fp=0xc20806bd60 sp=0xc20806bd30
runtime.cgocallback_gofunc(0x44e68f, 0x419a9d, 0x40f2f0)
	/usr/lib/go/src/runtime/asm_amd64.s:766 +0x57 fp=0xc20806bd70 sp=0xc20806bd60
asmcgocall()
	/usr/lib/go/src/runtime/asm_amd64.s:649 +0x37 fp=0xc20806bd78 sp=0xc20806bd70
runtime.asmcgocall_errno(0x40f2f0, 0xc20806bdc8)
	/usr/lib/go/src/runtime/asm_amd64.s:626 +0xf fp=0xc20806bd80 sp=0xc20806bd78
runtime.cgocall_errno(0x40f2f0, 0xc20806bdc8, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0x10d fp=0xc20806bda8 sp=0xc20806bd80
github.com/taylorchu/git2go._Cfunc__go_git_diff_foreach(0x127ddc0, 0x100000001, 0xc200000001, 0x1, 0x0)
	/home/march/src/github.com/taylorchu/git2go/:336 +0x43 fp=0xc20806bdc8 sp=0xc20806bda8
github.com/taylorchu/git2go.(*Diff).ForEach(0xc20803e058, 0x6726b8, 0x2, 0x0, 0x0)
	/home/march/src/github.com/taylorchu/git2go/diff.go:272 +0x17e fp=0xc20806be28 sp=0xc20806bdc8
main.main()
	/home/march/next/main.go:40 +0x4ce fp=0xc20806bf98 sp=0xc20806be28
runtime.main()
	/usr/lib/go/src/runtime/proc.go:63 +0xf3 fp=0xc20806bfe0 sp=0xc20806bf98
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20806bfe8 sp=0xc20806bfe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x445080, 0x934480, 0x61d930, 0xf)
	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x934480, 0x61d930, 0xf)
	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/usr/lib/go/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x445080, 0x93c400, 0x616d30, 0xd)
	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x93c400, 0x616d30, 0xd)
	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
	/usr/lib/go/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/lib/go/src/runtime/mgc0.c:1386

goroutine 4 [finalizer wait]:
runtime.gopark(0x445080, 0x93c3f8, 0x61d350, 0xe)
	/usr/lib/go/src/runtime/proc.go:130 +0x105 fp=0xc208019730 sp=0xc208019700
runtime.goparkunlock(0x93c3f8, 0x61d350, 0xe)
	/usr/lib/go/src/runtime/proc.go:136 +0x48 fp=0xc208019758 sp=0xc208019730
runtime.runfinq()
	/usr/lib/go/src/runtime/malloc.go:727 +0xba fp=0xc2080197e0 sp=0xc208019758
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
created by runtime.createfing
	/usr/lib/go/src/runtime/malloc.go:707 +0x5e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208068fe8 sp=0xc208068fe0

```

**Comment by pks-t** [comment]
@taylorchu Eh, you're correct. Seems as if I worked on an outdated branch of mine.

**Comment by pks-t** [comment]
Interestingly enough the problem was not caused by an outdated copy but to a change of the GC behavior. When the GC kicks in it inspects uintptr values, causing invalid dereferences due to us storing callback data by arbitrary uinptrs. I have no idea why the issue did not occur previously, but it's fixed now (at least for me). @taylorchu could you please verify the fix?

**Comment by pks-t** [comment]
Short bump. Any remarks left?

**Comment by shurcooL** [comment]
Hi,

I believe there is a relatively minor (and fixable) problem with the code change in this PR (I got to this PR from commit 1bd338af5e7a329c8ec5bd85500350795d0793d2, which touches the relevant code). I have found a reproducible test case that causes a panic because the Go garbage collector triggers and removes something that shouldn't be removed (because there are no references to it in the Go world, only in the C world). (/cc @slimsag, thanks for reviewing my findings and suggesting a fix.)

I will create an issue with some steps you can follow to reproduce the issue.

I also have an MVP fix for the issue, that reliably resolves the problem. There's more than one way of doing it, so I welcome review and suggestions to change it, but I believe the general idea of the fix is sound, or at least in the right direction (basically, to keep a reference to the value in Go world memory so that it doesn't get GCed). I will create the PR and reference the issue.

**Comment by shurcooL** [comment]
I've made that issue with a reproducible failing test case in #218, and a PR that fixes it in #219.
